CREATE TABLE clients (
  id SERIAL PRIMARY KEY,
  cnpj VARCHAR(255) NOT NULL UNIQUE,
  cod_client VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(255),
  register_date TIMESTAMP NOT NULL
);