CREATE TABLE equipment (
    id SERIAL PRIMARY KEY,
    equipment_name VARCHAR(255) NOT NULL,
    serial_number VARCHAR(255) NOT NULL UNIQUE,
    carrier VARCHAR(255) NOT NULL,
    receiver VARCHAR(255) NOT NULL,
    enterprise_name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    model VARCHAR(255) NOT NULL,
    current INT NOT NULL,
    power INT NOT NULL,
    voltage INT NOT NULL,
    registration_date TIMESTAMP NOT NULL,
    priority VARCHAR(1) NOT NULL CHECK (priority IN ('A', 'B', 'C')),
    photo_url VARCHAR(255),
    connectors VARCHAR(3) NOT NULL CHECK (connectors IN ('SIM', 'NAO')),
    ihm VARCHAR(3) NOT NULL CHECK (ihm IN ('SIM', 'NAO')),
    carcass_damage VARCHAR(3) NOT NULL CHECK (carcass_damage IN ('SIM', 'NAO')),
    engine VARCHAR(3) NOT NULL CHECK (engine IN ('SIM', 'NAO')),
    engine_cables VARCHAR(3) NOT NULL CHECK (engine_cables IN ('SIM', 'NAO')),
    fan VARCHAR(3) NOT NULL CHECK (fan IN ('SIM', 'NAO')),
    fan_carcass VARCHAR(3) NOT NULL CHECK (fan_carcass IN ('SIM', 'NAO')),
    others VARCHAR(255)
);